[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Ritom Paul", email = "rittmann007@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.141.1",
    "networkx>=3.6.1",
    "pydantic>=2.13.5",
    "pymongo>=4.18.1",
    "python-dotenv>=1.2.3",
    "uvicorn>=0.53.0",
]

[project.scripts]
backend = "backend:main"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"
